### PR TITLE
Bug/spurious user not found

### LINKED ISSUE #154: Spurious user not found messages
`[Debug] User not found (vendor-7b73bd566d.js, line 21541, x4)` is logged on first boot. Related to angular-eha.couchdb-auth.

### LINKED ISSUE #335: Rounds aren't shown until state is chosen
If I log in as gis user (who has Kano state role), the state dropdown correctly selects Kano, but no rounds are shown on the homepage (after #257) until I reselect Kano from the dropdown.

### LINKED ISSUE #346: Navbar: refreshing page resets state selection
When logged in as a user that has access to all states information (e.g. super) and selecting a state other than the default (current default: Bauchi), refreshing the page causes the state the be reset to the default state.  This is a minor bug but is inconvenient, particularly on the reports page.

This was discovered because the "invoice" side bar nav is slow to react to a click and I refreshed the page to see if it was reacting at all.

env: dev-dd.ehealth.org.ng

### PR DESCRIPTION
**Pull request by Chima1707**
closes #335 closes #346

### CODE REVIEW

**Comment by tlvince** [comment]
@Chima1707 looks like this pull request has become conflated with #353? In the issue (#154), we'd mentioned the fix for this is to remove or make logging configurable in eha-couchdb.auth. Should this PR be closed without merging?

**Comment by Chima1707** [comment]
It should be merged. While investigating #154, i saw a bug that has to do with state selection when a user logs out or comes to the dashboard for the first time so i used that opportunity to fix it

File: src/app/components/navbar/navbar.controller.js [hunk 1]
```diff
@@ -6,21 +6,35 @@ angular.module('navbar')
...
+      console.log(state, 'selected')
+      userStateService.setUserSelectedState(state)
+        .then(function (status) {
+          if (status) {
+            $rootScope.$broadcast('stateChanged', { state: { name: state } })
+          }
+        })
     }
+
+    $scope.name = config.name
```
Comment (tlvince) [inline src/app/components/navbar/navbar.controller.js:34]: Why the use of `$scope` and `vm` (`controller as`)? We prefer `controller as`.

File: src/app/components/navbar/navbar.controller.js [hunk 2]
```diff
@@ -6,21 +6,35 @@ angular.module('navbar')
...
+    }
+
+    initializeStateMap()
+
+    $scope.stateMap = userStateService.stateMap
+
+    $scope.selectState = function (state) {
+      console.log(state, 'selected')
+      userStateService.setUserSelectedState(state)
+        .then(function (status) {
```
Comment (tlvince) [inline src/app/components/navbar/navbar.controller.js:24]: Needs error handling (`catch` block).

File: src/app/components/navbar/navbar.html [hunk 3]
```diff
@@ -17,61 +17,46 @@
...
-            <span class="caret"></span>
-          </button>
-          <ul class="dropdown-menu" role="menu">
-            <li>
-              <a class="pointer" ng-click="navbarCtrl.toggleCollapse(); navbarCtrl.logout()">Logout</a>
-            </li>
-          </ul>
-        </div>
-      </ul>
+    <eha-dropdown-menu
```
Comment (tlvince) [inline src/app/components/navbar/navbar.html:43]: Do we really need a directive for this? To me, this is over engineering it.

File: src/app/components/utility/userStateService.js [hunk 4]
```diff
@@ -0,0 +1,124 @@
+/**
+ * Created by chima on 11/19/15.
+ */
+'use strict'
+
+angular.module('utility')
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: I'd suggest this service should be merged into `authService`.

File: src/app/components/utility/userStateService.js [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+      self.stateMap.selectedState = ''
+    }
+
+    this.getUserSelectedState = function (byId) {
+      return ehaCouchDbAuthService.getCurrentUser()
+        .then(function (user) {
+          if (!user.userCtx.name) {
+            return ''
+          }
+          return $localForage.getItem(user.userCtx.name)
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: `$localForage` isn't a top-level dependency (it's a transitive dependency from eha.couchdb-auth). Good idea to store the user's previously selected state though (from a UX point of view). localforage will need adding as a top-level dependency (in `bower.json`). (Later, I'd be tempted to replace this with [PouchDB local docs](http://pouchdb.com/guides/local-documents.html), though there's little point until pluggable local storage wrapper support is added to eha.couchdb-auth).

File: src/app/components/utility/userStateService.js [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+            .then(function (state) {
+              var result = !byId ? state : (byId === true ? self.getState(state, true) : self.getState(state))
+              return $q.when(result)
+            })
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: Error handling?

File: src/app/components/utility/userStateService.js [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+        })
+    }
+
+    this.setUserSelectedState = function (state) {
+      return ehaCouchDbAuthService.getCurrentUser()
+        .then(function (user) {
+          if (!state || !user.userCtx.name) {
+            return $q.when('')
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: Might be more appropriate to reject here?

File: src/app/components/utility/userStateService.js [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+          }
+          return $localForage.setItem(user.userCtx.name, state)
+            .then(function (st) {
+              return true
+            })
+        })
+    }
+
+    this.getState = function (name, byId) {
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: I'm not keen on storing the entire states list in local storage. Can't we just fetch them in the login promise chain?

File: src/app/components/utility/userStateService.js [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+          return locationService.getLocationsByLevel(LEVEL)
+        }
+        var stateIds = self.authorisedStates(user)
+        return locationService.getLocationsByLevelAndId(LEVEL, stateIds)
+      }
+
+      return ehaCouchDbAuthService.getCurrentUser().then(getStatesByUser)
+    }
+
+    this.authorisedStates = function (user) {
```
Comment (tlvince) [inline src/app/components/utility/userStateService.js]: Duplicated in `authService`.

File: src/app/components/utility/userStateService.js (hunk 8 above)
Comment (Chima1707) [inline src/app/components/utility/userStateService.js]: Remember, when a user refreshes the page, the states variable resets to undefined even if the user is already logged in. And we cant be fetching the states when the user visits the site for the first time since we don't even know who the user is and the states he has access to at that point. what i did was fetch the user states at login time and cache it using localForage till the user logs out.

File: src/app/configurations/allocations/calculations/calculations.controller.spec.js [hunk 10]
```diff
@@ -41,6 +41,9 @@ describe('CalculationsController', function () {
           return $q.when([])
         })
       })
+      $provide.service('userStateService', function () {
```
Comment (tlvince) [inline src/app/configurations/allocations/calculations/calculations.controller.spec.js]: Just as a tip, I like to use `angular.noop` in these situations, e.g.: `$provide.service('userStateService', angular.noop)`

File: src/app/components/utility/userStateService.js (hunk 9 above)
Comment (Chima1707) [inline src/app/components/utility/userStateService.js]: Yea, their was cyclic dependency but i really needed that function, may be i would have to go with the option of implementing the userStatesService features inside AuthService

File: src/app/configurations/allocations/calculations/calculations.states.js [hunk 11]
```diff
@@ -21,13 +21,8 @@ angular.module('allocations')
...
           },
-          locationStates: function (locationService) {
-            var keys = []
-            keys.push(['2', 'NG']) // TODO: get this from auth
-            return locationService.getByLevelAndAncestor(keys)
-              .catch(function () {
-                return []
-              })
+          locationStates: function (locationService, userStateService) {
+            return userStateService.getUserSelectedState('object')
```
Comment (tlvince) [inline src/app/configurations/allocations/calculations/calculations.states.js]: I'm not sure what passing in `'object'` does by looking at it.

File: src/app/components/utility/userStateService.js (hunk 4 above)
Comment (Chima1707) [inline src/app/components/utility/userStateService.js]: I would look into that tonite

File: src/app/home/home.states.js [hunk 12]
```diff
@@ -14,13 +14,12 @@ angular.module('home')
...
+        roundReport: function (deliveryRoundService, userStateService) {
           var key = ''
           var roundInfo = []
-          return indexService.getUserStates()
-            .then(function (states) {
-              var defaultState = angular.isArray(states) && states.length > 0 ? states[0]._id : ''
-              var state = angular.isDefined($rootScope.selectedState) ? $rootScope.selectedState._id : defaultState
+          return userStateService.getUserSelectedState()
+            .then(function (state) {
+              state = state || userStateService.stateMap.selectedState
```
Comment (tlvince) [inline src/app/home/home.states.js]: What if `userStateService.stateMap.selectedState` is falsy?

File: src/app/components/navbar/navbar.html (hunk 3 above)
Comment (Chima1707) [inline src/app/components/navbar/navbar.html:43]: Yes, it looks like that, but its all about code reuse. i also used it in the username/logout menu, and i  think we might still have another menu, who knows

File: src/app/reports/menu/menu.html [hunk 13]
```diff
@@ -11,12 +11,7 @@
       <span>Utility</span>
     </h4>
   </a>
-  <a ui-sref="reports.layout.facility" ui-sref-active="active" class="list-group-item">
```
Comment (tlvince) [inline src/app/reports/menu/menu.html:14]: Why was this removed?

File: src/app/reports/reports.service.js [hunk 14]
```diff
@@ -6,23 +6,38 @@ angular.module('reports')
...
+          options.endkey = [state, {}]
+
+          return $q.all([dbService.getView('reports/delivery-rounds', options), _this.getRoundsCount(state)])
+            .then(function (response) {
+              return {
+                total: response[1].rows.length > 0 ? response[1].rows[0].value : 0,
+                offset: response.offset,
+                results: pouchUtil.pluckValues(response[0])
+              }
+            }).catch(function () {})
```
Comment (tlvince) [inline src/app/reports/reports.service.js]: Why silence the error?

**Comment by tlvince** [comment]
Planning schedule page has broken. Throws:

```
[Error] Error: undefined is not an object (evaluating '$scope.selectedState._id')
loadDrivers@http://localhost:3000/app/planning/schedule/schedule-round.controller.js:41:39
http://localhost:3000/app/planning/schedule/schedule-round.controller.js:190:16
invoke@http://localhost:3000/bower_components/angular/angular.js:4478:22
instantiate@http://localhost:3000/bower_components/angular/angular.js:4486:33
http://localhost:3000/bower_components/angular/angular.js:9151:39
http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4018:39
invokeLinkFn@http://localhost:3000/bower_components/angular/angular.js:8789:15
nodeLinkFn@http://localhost:3000/bower_components/angular/angular.js:8289:23
compositeLinkFn@http://localhost:3000/bower_components/angular/angular.js:7680:23
publicLinkFn@http://localhost:3000/bower_components/angular/angular.js:7555:45
updateView@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3959:34
http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3921:21
$broadcast@http://localhost:3000/bower_components/angular/angular.js:16311:33
http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3311:32
processQueue@http://localhost:3000/bower_components/angular/angular.js:14745:30
http://localhost:3000/bower_components/angular/angular.js:14761:39
$eval@http://localhost:3000/bower_components/angular/angular.js:15989:28
$digest@http://localhost:3000/bower_components/angular/angular.js:15800:36
http://localhost:3000/bower_components/angular/angular.js:16028:33
completeOutstandingRequest@http://localhost:3000/bower_components/angular/angular.js:5507:15
http://localhost:3000/bower_components/angular/angular.js:5784:33 – "<ui-view class=\"ng-scope\">"
    (anonymous function)
    (anonymous function)
    invokeLinkFn
    nodeLinkFn
    compositeLinkFn
    publicLinkFn
    updateView
    (anonymous function)
    $broadcast
    (anonymous function)
    processQueue
    (anonymous function)
    $eval
    $digest
    (anonymous function)
    completeOutstandingRequest
    (anonymous function)
```

File: src/app/configurations/allocations/calculations/calculations.states.js (hunk 11 above)
Comment (Chima1707) [inline src/app/configurations/allocations/calculations/calculations.states.js]: passing object will give the full state object, passing true will return the state name like "KN","BA", while passing nothing will give the state ID

Comment (tlvince) [inline src/app/configurations/allocations/calculations/calculations.states.js]: OK, but maybe it'd be better to split that method into several helpers with descriptive names rather than relying on magic strings/params.

File: src/app/home/home.states.js (hunk 12 above)
Comment (Chima1707) [inline src/app/home/home.states.js]: Asynchronous codes run side by side. setUserSelectedState sets the user selected state asynchronously, so its possible that localForage doesnt have the user state stored completely before this part of the application gets called. I saw this happened some few times especially at home.states case immediately a user logs in. So, if you try to call  getUserSelectedState you wont get any state returned yet. so what i did was, since i already knew that a stateMap.selectedState variable will be already set, so i get from it.The callback for localForage.getItem was called before the callback for localForage.setItem. and both of them are from different parts of the application, so i couldn't sequence them. UserStateService, and home.states

File: src/app/configurations/allocations/calculations/calculations.states.js (hunk 11 above)
Comment (Chima1707) [inline src/app/configurations/allocations/calculations/calculations.states.js]: this particular function is asking for the object version of the selected state

File: src/app/reports/menu/menu.html (hunk 13 above)
Comment (Chima1707) [inline src/app/reports/menu/menu.html:14]: it was a duplicate, i think, i confirmed from my other team members, Musa before removing it

File: src/app/configurations/allocations/calculations/calculations.states.js (hunk 11 above)
Comment (tlvince) [inline src/app/configurations/allocations/calculations/calculations.states.js]: Yeah, I see what you mean.

However, from perspective of someone who's reading this for the first time, I'd expect `userStateService.getUserSelectedState()` to return the state, be it a string or object. Without reading it's implementation, it's not obvious what the return value should be by passing in a parameter (true or `'object'`).

I would split it up into the following signatures:

`userStateService.getUserSelectedState`
`userStateService.getUserSelectedStateName`
`userStateService.getUserSelectedStateId`

Martin Fowler has a piece on this: [Flag argument](http://martinfowler.com/bliki/FlagArgument.html).

Sorry to derail this PR.

File: src/app/reports/menu/menu.html (hunk 13 above)
Comment (tlvince) [inline src/app/reports/menu/menu.html:14]: So for example, https://dev-dd.ehealth.org.ng/#/reports/facility is duplicated with https://dev-dd.ehealth.org.ng/#/facility/faulty? Those views are showing different results. Maybe removing it should be left for a separate issue (with discussion)?

File: src/app/components/navbar/navbar.controller.js (hunk 2 above)
Comment (Chima1707) [inline src/app/components/navbar/navbar.controller.js:24]: added error catch block

File: src/app/components/utility/userStateService.js (hunk 5 above)
Comment (Chima1707) [inline src/app/components/utility/userStateService.js]: fixed

File: src/app/reports/menu/menu.html (hunk 13 above)
Comment (Chima1707) [inline src/app/reports/menu/menu.html:14]: Ok

**Comment by tlvince** [comment]
From https://github.com/eHealthAfrica/direct-delivery-dashboard/pull/353#issuecomment-159960715:

image
the state drop down now shows undefined on allocations/calculations

File: src/app/reports/menu/menu.html (hunk 13 above)
Comment (tlvince) [inline src/app/reports/menu/menu.html:14]: Opened an issue at https://github.com/eHealthAfrica/direct-delivery-dashboard/issues/360

Comment (tlvince) [inline src/app/reports/menu/menu.html:14]: Could you revert removing it from here?

File: src/app/components/navbar/navbar.html (hunk 3 above)
Comment (tlvince) [inline src/app/components/navbar/navbar.html:43]: OK lets go with this.

File: src/app/configurations/allocations/calculations/calculations.states.js (hunk 11 above)
Comment (tlvince) [inline src/app/configurations/allocations/calculations/calculations.states.js]: Could you put in an XXX (potentially confusing) comment in for now so we can look at this later?

**Comment by tlvince** [comment]
@Chima1707 thanks. Could you confirm "the state drop down now shows undefined on allocations/calculations"?

**Comment by tlvince** [comment]
Still not sure about removing `reports.layout.facility` from the menu, but otherwise looks good to me.

**Comment by Chima1707** [comment]
@tlvince I have added reports.layout.facility, please review the latest commit

**Comment by tlvince** [comment]
@Chima1707 I noticed that if you log in as `super` and choose Bauchi, log out and login as `gis`, Bauchi remains selected (even though `gis` does not have access to Bauchi).

This is because `states` and `selectedState` aren't cleared when the user logs out.

**Comment by tlvince** [comment]
`localForage` still needs adding to `bower.json` btw.

**Comment by Chima1707** [comment]
@tlvince  fixed it. Please review

**Comment by tlvince** [comment]
:+1:
